openapi: "3.0.0"
info:
  title: "Express Template"
  version: "1.0.0"
  description: "API documentation for a basic Express Template"

servers:
  - url: http://localhost:4000
    description: Local server
